FROM python:slim as base

RUN mkdir -p /money
WORKDIR /money
COPY ./requirements.txt .
COPY ./pyproject.toml   .
COPY ./poetry.lock      .
COPY ./money            ./money
RUN pip install -r ./requirements.txt
RUN poetry install

EXPOSE 80
ENV PORT=80
CMD [ "poetry", "run", "python", "-m", "money" ]