schema {
  query: GqlQuery
  mutation: GqlMutations
}

type GqlUserAggregateObject {
  uuid: String!
  firstName: String!
  lastName: String!
  username: String!
  email: String!
  hashedPassword: String!
  lastLogin: DateTime
}

"""
The `DateTime` scalar type represents a DateTime
value as specified by
[iso8601](https://en.wikipedia.org/wiki/ISO_8601).
"""
scalar DateTime

type GqlQuery {
  GqlFindUserByUsernameQuery(username: String!): GqlFindUserByUsernameQuery
}

type GqlFindUserByUsernameQuery {
  user: GqlUserAggregateObject
}

type GqlMutations {
  GqlCreateUserCommandMutation(email: String!, firstName: String!, lastName: String!, password: String!, username: String!): GqlCreateUserCommandMutation
  GqlLogInCommandMutation(password: String!, username: String!): GqlLogInCommandMutation
}

type GqlCreateUserCommandMutation {
  ok: Boolean!
}

type GqlLogInCommandMutation {
  success: GqlUserAggregateObject
  failure: String
}
