query LoadUser($username: String!) {
  FindUserByUsername(username: $username) {
    user {
      email
      username
      lastLogin
    }
  }
}

mutation RegisterUser(
  $email: String!
  $lastName: String!
  $firstName: String!
  $username: String!
  $password: String!
) {
  CreateUserCommand(
    email: $email
    firstName: $firstName
    lastName: $lastName
    username: $username
    password: $password
  ) {
    ok
  }
}
